---
# does not include logic for cassandra_stargate boolean, applied @ the include

- name: Download binary build of stargate-core for cassandra
  get_url: url={{ cassandra_stargate_build_url }} dest=/tmp/stargate-core.tar.gz
  when: not cassandra_stargate_build_source

- name: Extract stargate-core into cassandra libs
  command: tar -C /opt/cassandra/{{ cassandra_home }}/lib --exclude=samples --strip-components=2 -zxpvf /tmp/stargate-core.tar.gz
  when: not cassandra_stargate_build_source

- name: Checkout code from Git for stargate-core for cassandra
  git: repo={{ cassandra_stargate_git_repo }}
       dest=/tmp/stargate_core_build
       version={{ cassandra_stargate_git_ref }}
  register: git_clone
  when: cassandra_stargate_build_source

- name: Add gradle wrapper to stargate-core sources
  copy: src=files/gradle-wrapper/ dest=/tmp/stargate_core_build
  when: cassandra_stargate_build_source and git_clone.changed

#- name: Set dummy username for maven publish
#  lineinfile: dest=/tmp/stargate_core_build/build.gradle regexp="^ossrhUsername" line="ossrhUsername = \"foo\"" insertafter="^version"
#  when: cassandra_stargate_build_source and git_clone.changed

- name: Fix build file
  replace: dest=/tmp/stargate_core_build/build.gradle regexp="(.*?)ossrh(Username|Password)(.*?)" replace="\1\"ossrh\2\"\3"
  when: cassandra_stargate_build_source and git_clone.changed

- name: Set permissions on gradlew script
  file: path=/tmp/stargate_core_build/gradlew mode=0755
  when: cassandra_stargate_build_source and git_clone.changed

- name: Run stargate-core build
  command: chdir=/tmp/stargate_core_build ./gradlew clean jar
  when: cassandra_stargate_build_source and git_clone.changed

#- name: Copy stargate-core dependencies to cassandra libs
#  shell: cp /tmp/stargate_core_build/build/dist/stargate/libs/* {{ cassandra_home }}/lib
#  when: cassandra_stargate_build_source and git_clone.changed

- name: Copy built stargate-core to cassandra libs
  shell: cp /tmp/stargate_core_build/build/libs/* {{ cassandra_home }}/lib
  when: cassandra_stargate_build_source and git_clone.changed

