---
jetty_version: '9.3.3.v20150827'
jetty_basename: 'jetty-distribution-{{ jetty_version }}'
jetty_filename: '{{ jetty_basename }}.tar.gz'
jetty_mirror: 'http://ftp.acc.umu.se/mirror/eclipse.org/jetty/stable-9/dist/{{ jetty_filename }}'
jetty_checksum: 'decd6788232646f9a2980c15aa076ecbd919e61867913d056ddb3251ac31415c'
jetty_root: '/opt/jetty'
jetty_temp: '{{ jetty_root }}/temp'
jetty_apps: '{{ jetty_root }}/apps'
jetty_install_dir: '{{ jetty_root }}/{{ jetty_basename }}'
jetty_user: 'jetty'
jetty_group: 'jetty'
# Used as generics for container user elsewhere, and switching behavior based on containers
servlet_container: 'jetty9'
servlet_container_user: '{{ jetty_user }}'
servlet_container_group: '{{ jetty_group }}'
